spring.application.name=resultMgtSys

spring.datasource.url=jdbc:postgresql://localhost:5432/studentRecordMgtSys
spring.datasource.username=cosmasndulue
spring.datasource.password=Christian123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#jwt.secret=mYablesecretsecretkeyformyjwt5673892354